name: pypi

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  distribution:
    uses: $/.github/workflows/distribution.yml

  pypi:
    needs: distribution
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: pypi
    steps:
      - name: Download the tested distribution
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: tested-distribution
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # release/v1
